LEXICON_RU: dict[str : str] = {
    '/start': 'Привет!\n\nЯ бот для изучения английского языка в стиле игры!\n\n'
              'Если хотите - можете мне что-нибудь прислать или '
              'отправить команду /help',
    '/help': 'Тут пока ничего нет :_)',
    '/other': 'Я еще не научился этому :_)',
    'prav_otv': 'Молодец\n\nТы ответил правильно😍',
    'neprav_otv': 'К сожалению ты ответил неправильно💩',
    
}

LEXICON_MAIN = [
  "hello",
  "world",
  "apple",
  "dog",
  "cat",
  "house",
  "car",
  "tree",
  "book",
  "pen",
  "paper",
  "computer",
  "phone",
  "music",
  "movie",
  "game",
  "sport",
  "food",
  "water",
  "air",
  "sun",
  "moon",
  "star",
  "cloud",
  "rain",
  "snow",
  "wind",
  "earth",
  "sea",
  "ocean",
  "mountain",
  "river",
  "lake",
  "island",
  "city",
  "town",
  "village",
  "street",
  "house",
  "apartment",
  "room",
  "bed",
  "table",
  "chair",
  "door",
  "window",
  "mirror",
  "picture",
  "bookshelf",
  "desk",
  "computer"
]


LEXICON_LENG: dict[str: str] ={
    "hello": "привет",
    "world": "мир",
    "apple": "яблоко",
    "dog": "собака",
    "cat": "кошка",
    "house": "дом",
    "car": "машина",
    "tree": "дерево",
    "book": "книга",
    "pen": "ручка",
    "paper": "бумага",
    "computer": "компьютер",
    "phone": "телефон",
    "music": "музыка",
    "movie": "фильм",
    "game": "игра",
    "sport": "спорт",
    "food": "еда",
    "water": "вода",
    "air": "воздух",
    "sun": "солнце",
    "moon": "луна",
    "star": "звезда",
    "cloud": "облако",
    "rain": "дождь",
    "snow": "снег",
    "wind": "ветер",
    "earth": "земля",
    "sea": "море",
    "ocean": "океан",
    "mountain": "гора",
    "river": "река",
    "lake": "озеро",
    "island": "остров",
    "city": "город",
    "town": "городок",
    "village": "деревня",
    "street": "улица",
    "apartment": "квартира",
    "room": "комната",
    "bed": "кровать",
    "table": "стол",
    "chair": "стул",
    "door": "дверь",
    "window": "окно",
    "mirror": "зеркало",
    "picture": "картина",
    "bookshelf": "книжная полка",
    "desk": "письменный стол",
    "computer": "компьютер"
}

LEXICON_COMMANDS: dict[str, str] = {
    '/start': 'Старт бота или перезагрузка',
    '/help': 'Помощь и о боте',

}

# LEXICON_MAIN_Update = [
#   "hello",
#   "world",
#   "apple",
#   "dog",
#   "cat",
#   "house",
#   "car",
#   "tree",
#   "book",
#   "pen",
#   "paper",
#   "computer",
#   "phone",
#   "music",
#   "movie",
#   "game",
#   "sport",
#   "food",
#   "water",
#   "air",
#   "sun",
#   "moon",
#   "star",
#   "cloud",
#   "rain",
#   "snow",
#   "wind",
#   "earth",
#   "sea",
#   "ocean",
#   "mountain",
#   "river",
#   "lake",
#   "island",
#   "city",
#   "town",
#   "village",
#   "street",
#   "house",
#   "apartment",
#   "room",
#   "bed",
#   "table",
#   "chair",
#   "door",
#   "window",
#   "mirror",
#   "picture",
#   "bookshelf",
#   "desk",
#   "computer",
#   "library",
#   "university",
#   "school",
#   "teacher",
#   "student",
#   "pencil",
#   "ruler",
#   "calculator",
#   "garden",
#   "park",
#   "beach",
#   "forest",
#   "hotel",
#   "restaurant",
#   "cafe",
#   "shop",
#   "market",
#   "bank",
#   "hospital",
#   "doctor",
#   "nurse",
#   "patient",
#   "football",
#   "basketball",
#   "tennis",
#   "swimming",
#   "cycling",
#   "running",
#   "jogging",
#   "gym",
#   "fitness",
#   "yoga",
#   "meditation",
#   "relaxation",
#   "holiday",
#   "vacation",
#   "travel",
#   "adventure",
#   "exploration",
#   "biology",
#   "chemistry",
#   "physics",
#   "mathematics",
#   "history",
#   "geography",
#   "language",
#   "culture",
#   "art",
#   "music",
#   "dance",
#   "theater",
#   "film",
#   "photography",
#   "fashion",
#   "design",
#   "architecture",
#   "engineering",
#   "technology",
#   "robotics",
#   "astronomy",
#   "botany",
#   "zoology",
#   "ecology",
#   "environment",
#   "conservation",
#   "sustainability",
#   "recycling",
#   "energy",
#   "climate",
#   "weather",
#   "forecast",
#   "meteorology",
#   "geology",
#   "mineralogy",
#   "petrology",
#   "seismology",
#   "anthropology",
#   "sociology",
#   "psychology",
#   "philosophy",
#   "literature",
#   "poetry",
#   "novel",
#   "story",
#   "essay",
#   "article",
#   "journalism",
#   "communication",
#   "media",
#   "broadcasting",
#   "internet",
#   "network",
#   "computer science",
#   "algorithm",
#   "data",
#   "information",
#   "knowledge",
#   "intelligence",
#   "artificial intelligence",
#   "machine learning",
#   "deep learning",
#   "neural network",
#   "database",
#   "software",
#   "hardware",
#   "cloud computing",
#   "cybersecurity",
#   "networking",
#   "programming",
#   "coding",
#   "debugging",
#   "testing",
#   "deployment",
#   "maintenance",
#   "update",
#   "upgrade",
#   "migration",
#   "integration",
#   "interface",
#   "user experience",
#   "human-computer interaction",
#   "virtual reality",
#   "augmented reality",
#   "mixed reality",
#   "artificial general intelligence",
#   "natural language processing",
#   "computer vision",
#   "robotic process automation",
#   "business intelligence",
#   "data analytics",
#   "data mining",
#   "data science",
#   "machine vision",
#   "computer-aided design",
#   "computer-aided manufacturing",
#   "3D printing",
#   "additive manufacturing",
#   "digital twin",
#   "industrial internet of things",
#   "smart manufacturing",
#   "Industry 4.0",
#   "blockchain",
#   "cryptocurrency",
#   "bitcoin",
#   "ethereum",
#   "smart contract",
#   "distributed ledger",
#   "decentralized application",
#   "initial coin offering",
#   "token sale",
#   "cryptographic hash function",
#   "public-key cryptography",
#   "private key",
#   "wallet",
#   "mining"
# ]